[package]
name = "json2cbor"
version = "1.0.0"
authors = ["Tim Hutt <tdhutt@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.102"
serde_json = "1.0.41"
serde_cbor = "0.10.2"
serde-transcode = "1.1.0"
anyhow = "1.0"
